refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      # pattern: "{d} - {m}{n}"
      pattern: "{h({d(%H:%M:%S.%3f)} [{l}]:)} {m}{n}"

root:
  level: debug
  appenders: [ stdout ]

loggers:
  app::backend::db:
    level: info
  app::requests:
    level: info
    appenders:
      - requests
    additive: false
  rustls::client:
    level: warn

  ureq:
    level: warn