[package]
name = "sandbox01"
version = "0.0.1"
edition = "2021"

[dependencies]
lamecore = { path = "../lamecore" }
log = { workspace = true }
log4rs = { workspace = true }
tokio = { workspace = true }
